# Base stage to install dependencies
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Expose port 5173 for Vite dev server (default)
# EXPOSE 5173

# Start the Vite dev server for development
CMD ["npm", "run", "dev"]